### ISSUE TITLE
업로드 관련 질문 !

### ISSUE THREAD

**Issue by dahunlim** [capstone-jicos/Ongi-server#3]
업로드가 진행되는게 궁금한데 만약 프로필 사진을 수정한다고 치면

마이 페이지 내정보 수정 화면에서 프로필 사진을 수정을 눌러서 사진을 등록하는 순간

독립적으로 업로드기능이 수행되고 자체적으로 S3 url 주소를 가지고 있다가 수정 완료 버튼을 누르면 S3 Url 주소랑 다른 정보들이 넘어오는게 맞는거야 ?

아니면 나중에 다른 정보들이랑 같이 사진 파일 자체가 넘어와서 라우팅 해주는 곳에서 upload를 호출해주는거야 ?

내생각에는 전자가 맞다고 생각하는데 맞는가 싶어서

**Comment by lkaybob** [comment]
내가 생각했던건 후자였긴 했어. 한꺼번에 올라가서, 사진파일을 먼저 S3에 올려서 미들웨어로 S3 URL을 넘겨받고, 최종 콜백에서 디비에 커밋하는 걸 생각했어.

근데 생각해보니 독립적인 업로드 기능이 있는 것이 더 현실적이긴 하겠다... 다만, 독립적인 업로드를 해놓으면 들어온 파일이 정당하게 들어온 것이지 검증하는게 필요할 거 같아. 예를 들어, 업로드 기능만 집중적으로 조지는(?) 공곡이 들어올 수 있으니...??

**Comment by dahunlim** [comment]
만약 후자로 진행을 하게 될때 프로필 이미지랑 회원정보중 하나를 동시에 수정하려고 할때 

수정하려는 데이터랑 이미지 파일 데이터가 같이 리퀘스트가 날아가야할텐데 그럼 form-data 형식으로 날아가야할텐데 거기서 키값을 잡아보려고하는데 잘 안되는데 이게 무슨 다른방법이 있는거야 아니면 원래 안되는거야 ?

**Comment by lkaybob** [comment]
그게 아마 formdata를 파싱하는 것이 필요할거야. 그래서 사용하는 것이 `formidable` 패키지인건데, 나도 실제로 사용해보진 않아서 안 되는 이유에 대해서는 확인해봐야할 것 같아. 지금은 아마 서버 패키지 전역에서 `app.use`를 사용하지 않고 부분적으로만 사용하는거 같은데, 그래서 아마 form-data를 제대로 파싱 못하는 거지 않을까 해.

혹시 작업하고 있는 부분만 해서 gist로 보여줄 수 있어?

**Comment by dahunlim** [comment]
아아 성민이 코드에 있던 formidable패키지가 그거였구나 그러면 할수 있을거같다!

일단 패키지 조금더 찾아보고 해보고 안되면 다시 물어볼게 !!

**Comment by lkaybob** [comment]
서버가 떠있을 때 업로드를 두 번 이상 수행하면 에러를 뿜으면서 서버가 죽음
```
/vagrant/node_modules/async/dist/async.js:966
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /vagrant/node_modules/async/dist/async.js:966:32
    at /vagrant/dist/lib/upload/index.js:32:17
    at IncomingForm.<anonymous> (/vagrant/dist/lib/upload/UploadService.js:30:9)
    at emitNone (events.js:111:20)
    at IncomingForm.emit (events.js:208:7)
    at IncomingForm._maybeEnd (/vagrant/node_modules/formidable/lib/incoming_form.js:557:8)
    at /vagrant/node_modules/formidable/lib/incoming_form.js:238:12
    at WriteStream.<anonymous> (/vagrant/node_modules/formidable/lib/file.js:79:5)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:613:14)
    at afterWrite (_stream_writable.js:464:3)
    at onwrite (_stream_writable.js:454:7)
    at fs.js:2239:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:2205:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! np@0.3.0 start: `node dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the np@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-11-22T01_21_14_936Z-debug.log
```

async 사용하는 것과 관련된 에러인 것 같은데, 확인 필요
